### ISSUE TITLE
第7回課題について

### ISSUE THREAD

**Issue by castero1219** [junko113/gz#3]
財前さん
コスゲです。課題の件ありがとうございました。
https://github.com/junko113/gz/tree/c97c880/07_23_zaiznjunko
こちらのURLで確認をさせていただきました！

基本的な内容をしっかりとやられた形ですね！
あとは初回の授業であったhtmlspecialcharas関数を使ったサニタイズ処理など、一緒に実装してみてください！

https://osushi.love/

ちょうどこのサービスが今日リリースされていたのですが、色々脆弱性がすごかったり、やっちゃいけないことを結構やっていたりでちょうどみなさんにとってある意味勉強になるところなので、togetterなどで記事もあるので、ぜひみてみてください！

あとは
echo '<tr><td>' . $result['book_name'] . '</td><td>' . $result['url'] 
		 .'</td><td>' . $result['comment'] . '</td><td>' . $result['time'] ."</td></tr>\n";

の箇所は、HTMLの中に変数を埋め込む形で対応すると今後色々なユースケースに対応できるようになると思います！
こちらも合わせてチェックしてみてくださいね！

<tr><td><?=$result['book_name']=?></td></tr>

みたいな形ですね！
よろしくお願いいたします！

**Comment by junko113** [comment]
コスゲさん
フィードバック有難うございます！
いつも授業でもお世話になっております。

htmlspecialcharas関数を使ったサニタイズ処理。。どのような処理かパッと思い出せなかったので、復習も兼ねて次回以降使ってみます。
https://osushi.love/さんは、初めて知りました。週末に見てみたいと思います。
作成するアプリは、いつも時間がなく中途半端になってしまうのですが、折角からばきちんと世に公開出来るWEBアプリを作る技術を身に着けたい気持ちがあるので、このような「やっちゃいけないこと」の情報は大変有難いです。。！
HTML埋め込みの対応についても承知しました。

以上よろしくお願い致します。
